"""Promotion planner: decide *where* and *how* to add packages to a
declarative configuration.

Strategy selection (in order):

1. ``EXTEND`` — an existing ``environment.systemPackages`` (or
   ``home.packages``) list is available; append entries there.
2. ``CREATE_MODULE`` — the root configuration parses and already imports
   modules; write ``<root>/nixorcist/<group>.nix`` and add it to ``imports``.
3. ``EMBED`` — no imports list exists; add a new
   ``environment.systemPackages`` binding in the root configuration.

If none of these is possible the plan raises ``TN009``; Nixorcist never
guesses how to edit a configuration it cannot parse.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from ..cli.diagnostics import Diagnostic, ErrorCode, NixorcistError
from ..core.models import ResolvedPackage
from ..nix.ast import find_binding, list_of
from .discover import ConfigurationModel


class PromotionPlanError(NixorcistError):
    pass


@dataclass
class PromotionPlan:
    strategy: str
    target_module: Path
    element_snippets: list[str] = field(default_factory=list)
    groups: list[tuple[str, list[ResolvedPackage]]] = field(default_factory=list)
    with_pkgs: bool = False
    attrpath: tuple[str, ...] | None = None
    new_module_path: Path | None = None
    new_module_content: str | None = None
    # Demotion fields
    remove_elements: list[str] = field(default_factory=list)
    remove_module_rel: Path | None = None
    removal_targets: list[tuple[str, tuple[str, ...]]] = field(default_factory=list)

    @property
    def changed_relative_files(self) -> list[str]:
        if self.strategy == "CREATE_MODULE":
            root = self.target_module.parent
            files = [str(self.new_module_path)]
            rel = self.target_module.relative_to(root) if self.target_module.is_relative_to(root) else Path(self.target_module.name)
            files.append(str(rel))
            return sorted(dict.fromkeys(files))
        if self.strategy == "REMOVE_MODULE":
            files = [str(self.remove_module_rel or "")]
            root = self.target_module.parent
            rel = self.target_module.relative_to(root) if self.target_module.is_relative_to(root) else Path(self.target_module.name)
            files.append(str(rel))
            return sorted(dict.fromkeys(files))
        rel = self.target_module
        return [str(rel)]


def _module_content(group_name: str, packages: list[ResolvedPackage]) -> str:
    attrs = [p.attribute for p in packages]
    joined = "\n".join(f"    {a}" for a in attrs)
    return (
        "# Generated by nixorcist. Do not edit by hand.\n"
        "{ pkgs, ... }:\n"
        "{\n"
        "  environment.systemPackages = with pkgs; [\n"
        f"{joined}\n"
        "  ];\n"
        "}\n"
    )


def _slug(name: str) -> str:
    safe = "".join(ch if ch.isalnum() else "-" for ch in name.lower())
    return safe.strip("-") or "packages"


def plan_promotion(
    model: ConfigurationModel,
    groups: list[tuple[str, list[ResolvedPackage]]],
) -> PromotionPlan:
    root = model.root
    all_pkgs: list[ResolvedPackage] = []
    for _, pkgs in groups:
        for p in pkgs:
            if all(p.requested != existing.requested for existing in all_pkgs):
                all_pkgs.append(p)

    decl = model.preferred_declaration
    if decl is not None and decl.module.is_relative_to(root.directory):
        if decl.with_pkgs:
            snippets = [p.attribute for p in all_pkgs]
        else:
            snippets = [f"pkgs.{p.attribute}" for p in all_pkgs]
        return PromotionPlan(
            strategy="EXTEND",
            target_module=decl.module,
            element_snippets=snippets,
            groups=groups,
            with_pkgs=decl.with_pkgs,
            attrpath=decl.attrpath,
        )

    # No declarable list found: prefer a dedicated module.
    if model.can_write_root:
        root_mod = model.graph.root_module
        assert root_mod is not None and root_mod.ast is not None
        imports_binding = find_binding(root_mod.ast, ["imports"])
        imports_list = list_of(imports_binding.children[0]) if imports_binding else None
        module_rel = Path("nixorcist") / f"{_slug(groups[0][0])}.nix"
        full_content: list[str] = []
        for group_name, pkgs in groups:
            full_content.append(_module_content(group_name, pkgs))
        content = "\n".join(full_content)
        new_module = root.directory / module_rel
        if imports_list is not None:
            return PromotionPlan(
                strategy="CREATE_MODULE",
                target_module=root.entry_file,
                groups=groups,
                new_module_path=module_rel,
                new_module_content=content + "\n",
            )
        return PromotionPlan(
            strategy="EMBED",
            target_module=root.entry_file,
            element_snippets=[p.attribute for p in all_pkgs],
            groups=groups,
            with_pkgs=True,
            attrpath=("environment", "systemPackages"),
        )

    if not root.entry_file.exists():
        raise PromotionPlanError(
            Diagnostic(
                ErrorCode.PROMOTION,
                f"configuration entry {root.entry_file} does not exist",
            )
        )
    raise PromotionPlanError(
        Diagnostic(
            ErrorCode.PROMOTION,
            f"could not plan a promotion: configuration {root.entry_file} could not be parsed",
            suggestion="either add an explicit environment.systemPackages = [...]; list, "
            "or run 'nix eval' on the file to confirm it is valid Nix",
        )
    )


def plan_demotion(
    model: ConfigurationModel,
    group_name: str,
    packages: list[ResolvedPackage],
    metadata=None,
) -> PromotionPlan:
    """Plan the removal of a group's declarative representation.

    If the group was promoted as a dedicated module (metadata declaration ==
    "module") the module file is deleted and its import entry removed from the
    root configuration.  Otherwise every discovered target list is stripped of
    the group's package attributes (metadata declaration "inline").
    """
    from ..core.models import DeclarativeMetadata

    met = metadata if isinstance(metadata, DeclarativeMetadata) else DeclarativeMetadata.from_dict(metadata)
    attrs = list(dict.fromkeys([p.attribute for p in packages] + [p.requested for p in packages]))
    root_dir = model.root.directory

    if met.declaration == "module" and met.module:
        module_rel = Path(met.module)
        module_abs = root_dir / module_rel
        if module_abs.exists() or (module_rel.is_absolute() and module_rel.exists()):
            return PromotionPlan(
                strategy="REMOVE_MODULE",
                target_module=model.root.entry_file,
                groups=[(group_name, packages)],
                remove_module_rel=module_rel,
            )

    # Default: strip matching elements from every discovered list.
    targets: list[tuple[str, tuple[str, ...]]] = []
    for decl in model.declarations:
        rel = decl.module.relative_to(root_dir) if decl.module.is_relative_to(root_dir) else decl.module
        targets.append((str(rel), decl.attrpath))
    return PromotionPlan(
        strategy="REMOVE_ELEMENTS",
        target_module=model.root.entry_file,
        groups=[(group_name, packages)],
        remove_elements=attrs,
        removal_targets=targets,
    )